name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,gui]"
      - name: Build (PyInstaller)
        shell: pwsh
        run: |
          pyinstaller --clean -y packaging/pyinstaller_win.spec
          $v = "$env:GITHUB_REF_NAME"  # tag name
          $zip = "dist/SudokuTrainer-$v-win64.zip"
          if (Test-Path $zip) { Remove-Item $zip -Force }
          Compress-Archive -Path "dist/SudokuTrainer/*" -DestinationPath $zip -Force
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/SudokuTrainer-*-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
